$(function () {
	$("#proveedor").click(function(){
		$("#proveedorDetalle").addClass("block");
		$("#ordenDeCompraDetalle").removeClass("block");
		$("#inventarioDetalle").removeClass("block");
		$("#inventarioDetalle2").removeClass("block");
		$("#ordenDeVentaDetalle").removeClass("block");
		$("#clienteDetalle").removeClass("block");
	})
	$("#ordenDeCompra").click(function(){
		$("#proveedorDetalle").removeClass("block");
		$("#ordenDeCompraDetalle").addClass("block");
		$("#inventarioDetalle").removeClass("block");
		$("#inventarioDetalle2").removeClass("block");
		$("#ordenDeVentaDetalle").removeClass("block");
		$("#clienteDetalle").removeClass("block");
	})
	$("#inventario").click(function(){
		$("#proveedorDetalle").removeClass("block");
		$("#ordenDeCompraDetalle").removeClass("block");
		$("#inventarioDetalle").addClass("block");
		$("#inventarioDetalle2").addClass("block");
		$("#ordenDeVentaDetalle").removeClass("block");
		$("#clienteDetalle").removeClass("block");
	})
	$("#ordenDeVenta").click(function(){
		$("#proveedorDetalle").removeClass("block");
		$("#ordenDeCompraDetalle").removeClass("block");
		$("#inventarioDetalle").removeClass("block");
		$("#inventarioDetalle2").removeClass("block");
		$("#ordenDeVentaDetalle").addClass("block");
		$("#clienteDetalle").removeClass("block");
	})
	$("#cliente").click(function(){
		$("#proveedorDetalle").removeClass("block");
		$("#ordenDeCompraDetalle").removeClass("block");
		$("#inventarioDetalle").removeClass("block");
		$("#inventarioDetalle2").removeClass("block");
		$("#ordenDeVentaDetalle").removeClass("block");
		$("#clienteDetalle").addClass("block");
	})
})
